# -*- coding: utf-8 -*-
"""Notebook Analisis Data_Dian Ayu Azizah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZoYcncn4zcyEtriedQo0BYYG8j84TLD

# Proyek Analisis Data: Bike Sharing Dataset (day.csv)
- **Nama:** Dian Ayu Azizah
- **Email:** dianayua4523140@univpancasila.ac.id
- **ID Dicoding:** dianayu_azizah

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

- **Pertanyaan 1:** Bagaimana pengaruh kondisi cuaca (weathersit) terhadap rata-rata jumlah penyewaan sepeda harian selama tahun 2012?

  Keterangan:
    - Specific: Kondisi cuaca
    - Measureable: Rata-rata penyewaan sepeda
    - Action-Oriented: Penyesuaian stok sepeda
    - Relevant: Operasional bisnis
    - Time-bound: Tahun 2012

- **Pertanyaan 2:** Apakah terdapat perbedaan yang signifikan dalam pola jumlah penyewaan antara hari kerja (workingday) dan hari libur (holiday) pada musim gugur (season 3) di tahun 2011 dan 2012?

    Keterangan:
     - Specific: Hari kerja vs hari libur di musim gugur
    - Measureable: Jumlah penyewaan sepeda
    - Action-Oriented: Strategi pemasaran khusus hari libur
    - Relevant: Segmentasi pengguna
    - Time-bound: Tahun 2011-2012

- **Pertanyaan 3:** Bagaimana tren pertumbuhan total penyewaan sepeda secara keseluruhan dari tahun 2011 dibandingkan dengan tahun 2012?

    Keterangan:
     - Specific: Perbandingan total penyewaan antara tahun 2011 dan 2012 (*Year-over-Year*)
    - Measureable: Total jumlah penyewaan sepeda 'cnt'
    - Action-Oriented: Perencanaan ekspansi stasiun dan penambahan unit sepeda
    - Relevant: Evaluasi pertumbuhan dan keberhasilan bisnis secara tahunan
    - Time-bound: Periode data tahun 2011-2012

- **Pertanyaan 4:** Sejauh mana korelasi antara suhu udara (temperature) terhadap jumlah total penyewaan sepeda harian di seluruh musim?

    Keterangan:
     - Specific: Korelasi antara variabel suhu udara dengan jumlah penyewaan
    - Measureable: Koefisien korelasi dan grafik regresi linear
    - Action-Oriented: Prediksi stok sepeda (demand forecasting) berdasarkan ramalan cuaca
    - Relevant: Optimalisasi operasional berdasarkan faktor eksternal (suhu)
    - Time-bound: Data harian tahun 2011-2012

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Mengatur gaya visualisasi
sns.set_theme(style="whitegrid")

"""## Data Wrangling

### Gathering Data

#### Load day_df
"""

# Memuat dataset
day_df = pd.read_csv('day.csv')
day_df.head()

"""**Insight:** (Opsional)
- Dataset berhasil dimuat dengan 731 baris (mencakup data harian selama 2 tahun yaitu 2011-2012) dan 16 atribut/kolom yang berisi informasi waktu, kondisi cuaca, serta jumlah penyewaan sepeda.
- Fitur numerik seperti 'temp', 'atemp', 'hum', dan 'windspeed' sudah dalam bentuk ternormalisasi dalam skala 0-1, sehingga siap untuk proses analisis lebih lanjut.
- Berdasarkan sampel data awal, terdapat perbedaan pola antara pengguna 'casual' dan 'registered' di mana pengguna terdaftar cenderung mendominasi jumlah penyewaan pada hari kerja / 'workingday'.
- Kolom 'dteday' teredeteksi perlu dikonversi menjadi tipe data *datetime*, dan kolom kaetgorikal seperti 'season' dan 'weathersit' perlu dilakukan *mapping* supaya lebih informatif saat divisualisasikan.

### Assessing Data

#### Identifying Data Integrity and Quality Problem
"""

# Memeriksa info dataset (Tipe data, missing values)
print("--- Info Dataset ---")
print(day_df.info())

# Memeriksa duplikasi
print("\nJumlah duplikasi:", day_df.duplicated().sum())

# Memeriksa statistik deskriptif (mencari outlier/inaccurate value)
print("\n--- Statistik Deskriptif ---")
print(day_df.describe())

# Memeriksa missing values secara eksplisit
print("\n--- Missing Values ---")
print(day_df.isna().sum())

"""**Steps to Take:**
- Mengubah Tipe Data: Mengonversi atribut 'dteday' dari tipe data *object* menjadi *datetime* agar pengolahan data berbasis waktu (seperti pengelompokkan berdasarkan bulan atau tahun) dapat dilakukan dengan benar.
- Melakukan Mapping Kategorikal: Mengubah nilai numerik pada atribut 'season', 'yr', dan 'weathersit' menjadi label string (misalnya: 1 menjadi Spring, dan 0 menajdi 2011) untuk meningkatkan keterbacaan data saat proses analisis dan visualisasi.
- Pemeriksaan Outlier Potensial: Meninjau kembali nilai minimum pada atribut 'hum' yang bernilai 0.0, karena secara teknis kelembapan udara jarang mencapai nol mutlak, untuk memastikan apakah ini merupakan *inaccurate value* atau kondisi ekstrem.

**Insight:** (Opsional)
- Kualitas Data Sangat Baik: Tidak ditemukan adanya *missing values* pada seluruh atribut dan tidak juga terdapat data duplikat, sehingga inetgritas data untuk analisis sangat tinggi.
- Tipe Data Perlu Penyesuaian: Atribut 'dteday' masih bertipe object, yang secara teknis akan membatasi fungsi analisis *time-series* jika tidak diubah ke format datetime.
- Statistik Deskriptif: Rata-rata penyewaan sepeda harian 'cnt' berada di angka 4.504 unit, dengan rentang yang sangat lebar antara nilai minimum 22 hingga maksimum 8.714. Hal ini mengindikasikan adanya faktor eksternal (seperti cuaca atau hari libur) yang memberikan pengaruh terhadap fluktasi jumlah penyewa.
- Dominasi Pengguna Terdaftar: Rata-rata pengguna terdaftar 'registered' jauh lebih tinggi mencapai 3.356 pengguna dibandingkan pengguna kasual yang hanya mencapai 848 pengguna, menunjukkan bahwa baris pelanggan utama sistem ini adalah pengguna tetap/langganan.

### Cleaning Data

#### Fixing Data Type, Categorical Label, and Data Efficiency Problem
"""

# Mengubah tipe data dteday menjadi datetime
day_df['dteday'] = pd.to_datetime(day_df['dteday'])

# Mapping nilai kategori agar lebih informatif
day_df['season'] = day_df['season'].map({1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'})
day_df['yr'] = day_df['yr'].map({0: '2011', 1: '2012'})
day_df['mnth'] = day_df['mnth'].map({
    1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun',
    7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'
})
day_df['weathersit'] = day_df['weathersit'].map({
    1: 'Clear/Partly Cloudy',
    2: 'Misty/Cloudy',
    3: 'Light Snow/Rain',
    4: 'Heavy Rain/Ice'
})
day_df['weekday'] = day_df['weekday'].map({
    0: 'Sun', 1: 'Mon', 2: 'Tue', 3: 'Wed', 4: 'Thu', 5: 'Fri', 6: 'Sat'
})

# Mengubah tipe data menjadi 'category' (Tambahan Penting)
categorical_columns = ['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']
for col in categorical_columns:
    day_df[col] = day_df[col].astype('category')

# Menampilkan hasil pembersihan dan verifikasi tipe data
print(day_df.info())
day_df.head()

"""**Insight:** (Opsional)
- Konversi Tipe Data Sukses: Atribut 'dteday' sudah bertipe datetime64, yang memungkinkan saya melakukan analisis berbasis waktu secara akurat menggunakan fungsi-fungsi *time-series* di Python.
- Peningkatan Keterbacaann: Dengan melakukan *mapping* pada kolom kategorikal, data sekarang jauh lebih mudah dipahami. Contohnya, kita bisa langsung melihat bahwa tanggal 01-01-2011 adalah hari Sat (Sabtu) dengan cuaca Misti/Cloudy di musim Spring, bukan lagi sekadar angka kode.
- Efisiensi Memori: Penggunaan tipe data category berhasil menurunkan penggunaan memori dari 91.5 KB menjadi 58.0 KB (berkurang sekitar 36%). Hal ini bermanfaat untuk performa komputasi jika dataset bertambah besar.
- Kesiapan Visualisasi: Karena atribut kategorikal sudah memilik label string, maka saat saya membuat grafik nanti, sumbu grafik akan otomatis menampilkan nama musim/cuaca tanpa perlu kita atur secara menual satu per satu.

## Exploratory Data Analysis (EDA)

### Explore Pengaruh Cuaca Terhadap Penyewaan (2012)
Bagian ini menganalisis dampak kondisi cuaca terhadap jumlah penyewaan sepeda khusus pada tahun 2012. Analisis ini mencakup statistik deskriptif per kondisi cuaca serta melihat perbandingan perilaku antara pengguna tipe *casual* dan *registered*.
"""

# Mengambil data tahun 2012
df_2012 = day_df[day_df['yr'] == '2012']

# Agregasi penyewaan berdasarkan kondisi cuaca
weather_analysis = df_2012.groupby('weathersit', observed=True)['cnt'].agg(['mean', 'max', 'min', 'sum']).reset_index()

# Tambahan: Melihat persentase distribusi casual vs registered per cuaca
weather_user_type = df_2012.groupby('weathersit', observed=True)[['casual', 'registered']].mean().reset_index()

print("--- Analisis Cuaca 2012 ---")
print(weather_analysis)
print("\n--- Rata-rata Tipe Pengguna per Kondisi Cuaca ---")
print(weather_user_type)

"""**Insight:** (Opsional)
- Dominasi Cuaca Cerah: Kondisi *Clear/Partly Cloudy* memiliki rata-rata penyewaan tertinggi mencapai 6.003 dan total volume penyewaan yang sangat besar di atas 1,4 juta unit. Menunjukkan bahwa bisnis snagat bergantung pada kondisi cuaca yang baik.
- Dampak SIgnifikan Cuaca Buruk: Terjadi penurunan drastis pada rata-rata penyewaan saat cuaca berubah menjadi *Light Snow/Rain* hanya mencapai 2.126. Menunjukkan adanya risiko operasional yang tinggi dan penurunan permintaan hingga lebih dari 60% saat cuaca memburuk.
- Loyalitas Pengguna Registered: Menariknya, pada kondisi cuaca terburuk sekalipun, jumlah pengguna registered mencapai 1.809 tetap jauh lebih tinggi dibandingkan pengguna casual yang hanya mencapai 317. Kemungkinan besar pengguna 'registered' adalah pekerja/pelajar yang tetap harus bermobilitas meski cuaca kurang bersahabat, sementara pengguna 'casual' sangat dipengaruhi oleh kenyamanan cuaca.

### Explore Perbandingan Hari Kerja vs Hari Libur di Musim Gugur
Bagian ini mengeksplorasi perilaku penyewaan sepeda selama musim gugur (*Fall*) untuk membandingkan apakah terdapat perbedaan signifikan antara hari kerja (*workingday*) dan hari libur (*holiday/weekend*), serta melihat tren spesifiknya pada setiap bulan di musim tersebut.
"""

# Mengambil data musim gugur (Fall)
fall_df = day_df[day_df['season'] == 'Fall']

# Agregasi berdasarkan workingday untuk melihat rata-rata total penyewaan
workingday_analysis = fall_df.groupby('workingday', observed=True)['cnt'].agg(['mean', 'std', 'count']).reset_index()

# Tambahan: Melihat perbedaan performa pada setiap bulan di musim gugur
fall_monthly_analysis = fall_df.groupby(['mnth', 'workingday'], observed=True)['cnt'].mean().unstack()

print("--- Analisis Hari Kerja vs Libur (Musim Gugur) ---")
print(workingday_analysis)
print("\n--- Rata-rata Penyewaan per Bulan di Musim Gugur ---")
print(fall_monthly_analysis)

"""**Insight:** (Opsional)
- Korelasi Positif Kuat: Koefisien Pearson sebesar 0,6275 menunjukkan hubungan positif yang kuat antara suhu dan jumlah penyewaan. Secara statistik, kenaikan suhu cenderung diikuti dengan kenaikan jumlah penyewa.
- Ambang Batas Kenyamanan: Penyewaan mencapai puncaknya pada kategori suhu "Hangat" (5.547 sewa) dan "Panas" (5.610 sewa).
- Dampak Suhu Dingin: Sebaliknya, pada kategori suhu "Dingin", rata-rata penyewaan turun drastis hingga angka 1.819. Ini membuktikan bahwa kenyamanan termal merupakan faktor krusial yang menentukan keputusan masyarakat untuk menggunakan sepeda.

### Explore Tren Pertumbuhan Tahunan
Bagian ini untuk mengeksplorasi total penyewaa secara tahunan untuk melihat pertumbuhan bisnis dari tahun 2011 ke 2012.
"""

# Hitung total penyewaan harian
yearly_rentals = day_df.groupby('yr', observed=False)['cnt'].sum().reset_index()

# Cek apakah perlu di-mapping (Hanya jika nilainya masih 0 atau 1)
if yearly_rentals['yr'].iloc[0] in [0, 1]:
    yearly_rentals['yr'] = yearly_rentals['yr'].map({0: 2011, 1: 2012})

print("Total Penyewaan Tahunan:")
print(yearly_rentals)

"""**Insight:** (Opsional)
- Pertumbuhan Bisnis Masif: Terjadi lonjakan penyewaan yang sangat signifikan sebesar kurang lebih 64,8% secara *Year-over-Year*. Total sewa meningkat dari 1,24 juta pada tahun 2011 menjadi 2,04 juta pada tahun 2012.
- Indikator Keberhasilan: Pertumbuhan yang hampir dua kali lipat ini menunjukkan bahwa layanan bike sharing telah melewati fase adopsi awal dengan sukses dan memiliki basis pengguna yang berkembang pesat.

### Explore Pengaruh Suhu terhadap Minat Sewa
Bagian ini melihat hubungan antara suhu rata-rata harian dengan jumlah total penyewaan sepeda.
"""

# Menghitung korelasi Pearson antara suhu (temp) dan jumlah sewa (cnt)
correlation = day_df['temp'].corr(day_df['cnt'])

# Mendapatkan statistik deskriptif untuk kedua variabel
temp_stats = day_df[['temp', 'cnt']].describe()

print(f"Koefisien Korelasi Pearson antara Suhu dan Jumlah Sewa: {correlation:.4f}")
print("\nStatistik Deskriptif Suhu vs Jumlah Sewa:")
display(temp_stats)

# Melihat rata-rata penyewaan dalam rentang suhu tertentu (Binning sederhana)
# Mengelompokkan suhu menjadi 4 bagian (Dingin, Sejuk, Hangat, Panas)
day_df['temp_bins'] = pd.cut(day_df['temp'], bins=4, labels=['Dingin', 'Sejuk', 'Hangat', 'Panas'])
temp_analysis = day_df.groupby('temp_bins', observed=False)['cnt'].mean().reset_index()

print("\nRata-rata Penyewaan berdasarkan Kategori Suhu:")
display(temp_analysis)

"""**Insight:** (Opsional)
- Performa Hari Kerja Lebih Unggul: Di musim gugur, rata-rata penyewaan pada hari kerja sebesar 5.718, sedikit lebih tinggi dibandingkan hari libur/akhir pekan yang sebesar 5.474.
- Konsistensi vs Variansi: Nilai standar deviasi pada hari libur adalah 1.433, sedikit lebih rendah daripada hari kerja yang mencapai 1.470. Namun, keduanya menunjukkan angka cukup tinggi, menandakan flukatasi penyewaan di musim gugur masih dipengaruhi oleh faktor harian lainnya (seperti suhu spesifik harian).
- Tren Bulanan yang Unik: Pada bulan Agustus, terdapat perbedaan kontras di mana hari kerja jauh lebih tinggi sebesar 5.908 dibandingkan hari libur yang hanya 4.963. Namun, pada bulan Juni dan September, terjadi anomali di mana hari libur justru memiliki rata-rata penyewaan jauh lebih tinggi daripada hari kerja. Hal ini menunjukkan bahwa puncak musim gugur atau cuaca yang sejuk, masyarakat lebih cenderung menggunakan sepeda untuk rekreasi/menimati hari libur di akhir pekan.
-

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana pengaruh perbedaan kondisi cuaca (weathersit) terhadap rata-rata jumlah penyewaan sepeda harian selama tahun 2012?
"""

plt.figure(figsize=(10, 6))

# Menggunakan sns.barplot dengan minimalisasi elemen hiasan
ax = sns.barplot(
    x='weathersit',
    y='mean',
    data=weather_analysis,
    palette='viridis'
)

# Menambah label nilai di atas batang untuk meningkatkan Data-Ink Ratio (informasi langsung)
for p in ax.patches:
    ax.annotate(f'{p.get_height():.0f}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha = 'center', va = 'center',
                xytext = (0, 9),
                textcoords = 'offset points')

plt.title('Rata-rata Penyewaan Sepeda Berdasarkan Kondisi Cuaca (2012)', fontsize=14, pad=20)
plt.xlabel(None) # Menghapus label sumbu X karena kategori sudah jelas (meningkatkan ink ratio)
plt.ylabel('Rata-rata Jumlah Sewa', fontsize=12)

# Menerapkan sns.despine() untuk menghapus garis tepi atas dan kanan (Prinsip Tufte)
sns.despine()
plt.tight_layout()
plt.show()

"""**Insight:** (Opsional)
- Kondisi cuaca *Clear/Partly Cloudy* mendominasi dengan rata-rata 6.004 sewa, jauh mengungguli kondisi *Light Snow/Rain*.
- Penurunan drastis terjadi saat cuaca buruk *(Light Snow/Rain)* yang hanya mencapai 2.126 sewa. Menunjukkan bahwa operasional bisnis sangat rentan terhadap faktor cuaca.
- Bisa dipertimbangkan program loyalitas atau diskon khusus saat cuaca mendung/hujan ringan untuk menjaga kestabilan jumlah sewa.

### Pertanyaan 2: Bagaimana perbandingan pola penyewaan sepeda antara hari kerja (*workingday*) dan hari libur (*holiday/weekend*) pada setiap bulan di musim gugur (*Fall*)?
"""

plt.figure(figsize=(10, 6))

# Hanya menggunakan bulan pada musim gugur saja
month_order = ['Jun', 'Jul', 'Aug', 'Sep']

ax = sns.barplot(
    x='mnth',
    y='cnt',
    hue='workingday',
    data=fall_melted,
    palette='Set2',
    order=month_order
)

for p in ax.patches:
    if p.get_height() > 0:
        ax.annotate(f'{int(p.get_height()):,}',
                    (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha='center', va='center',
                    xytext=(0, 10),
                    textcoords='offset points',
                    fontsize=10,
                    fontweight='bold')

plt.title('Hari Kerja vs Hari Libur per Bulan (Musim Gugur)', fontsize=16, pad=25, loc='left')
plt.xlabel(None)
plt.ylabel('Rata-rata Jumlah Sewa', fontsize=12)
plt.legend(title=None, frameon=False, loc='upper center',
           bbox_to_anchor=(0.7, 1.0), ncol=2, fontsize=11)

# Memberi ruang ekstra di atas bar agar angka tidak terpotong frame
plt.ylim(0, fall_melted['cnt'].max() * 1.15)

sns.despine()
plt.tight_layout()
plt.show()

"""**Insight:** (Opsional)
- Pola penggunaan sepeda di musim gugur sangat dinamis; hari libur unggul di awal (Juni) dan akhir (September), sementara hari kerja memuncak di bulan Agustus.
- Pada bulan Juni, hari libur memiliki angka tertinggi (6.108), menunjukkan dominasi aktivitas rekreasi.
- Pada bulan Agustus, terjadi pergeseran di mana hari kerja mencapai angka tertinggi (5.908), kemungkinan karena aktivitas komuter kembali normal setelah masa libur.
- Secara keseluruhan, stabilitas angka di atas 5.000 menunjukkan bahwa pada musim gugur, baik pengguna komuter maupun rekreasional tetap aktif menggunakan sepeda.

### Pertanyaan 3: Bagaimana tren pertumbuhan total penyewaan sepeda secara keseluruhan dari tahun 2011 dibandingkan dengan tahun 2012?
"""

# Menyiapkan data (memastikan mapping yr benar)
yearly_df = day_df.groupby('yr', observed=False)['cnt'].sum().reset_index()
if yearly_df['yr'].iloc[0] in [0, 1]:
    yearly_df['yr'] = yearly_df['yr'].map({0: 2011, 1: 2012})

plt.figure(figsize=(10, 6))

# Menggunakan warna yang kontras untuk menunjukkan pertumbuhan
ax = sns.barplot(
    x='yr',
    y='cnt',
    data=yearly_df,
    palette='Blues',
    hue='yr',
    legend=False
)

# Menambahkan Anotasi Angka
for p in ax.patches:
    ax.annotate(f'{int(p.get_height()):,}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 10),
                textcoords='offset points',
                fontsize=12,
                fontweight='bold')

# Membersihkan Elemen Visual
plt.title('Total Pertumbuhan Penyewaan Sepeda (Year-over-Year)', fontsize=15, loc='left', pad=20)
plt.xlabel(None)
plt.ylabel('Total Penyewaan', fontsize=12)
plt.ylim(0, yearly_df['cnt'].max() * 1.15) # Memberi ruang untuk teks di atas batang

sns.despine() # Menghilangkan frame yang tidak perlu
plt.tight_layout()
plt.show()

"""**Insight:** (Opsional)
- Terjadi lonjakan bisnis masif sebesar 64.8% di tahun 2012.
- Kenaikan dari 1,24 juta ke 2,05 juta penyewaan menunjukkan bahwa layakan bike sharing ini telah melewati fase perkenalan yang kini berada di fase pertumbuhan cepat. Menunjukka indikator kuat bahwa pasar semakin menerima penggunaan sepeda sebagai moda transportasi atau rekreasi.

### Pertanyaan 4: Sejauh mana korelasi antara suhu udara (temperature) terhadap jumlah total penyewaan sepeda harian di seluruh musim?
"""

plt.figure(figsize=(10, 6))

# Menggunakan regplot dengan transparansi (alpha) untuk kejujuran sebaran data (Integritas)
sns.regplot(
    x='temp',
    y='cnt',
    data=day_df,
    scatter_kws={'alpha':0.3, 'color':'#2E86C1'},
    line_kws={'color':'#E74C3C', 'linewidth': 3},
    ci=None
)

# Menambahkan koefisien korelasi ke dalam plot (Integritas statistik)
corr_value = day_df['temp'].corr(day_df['cnt'])
plt.text(0.1, 8000, f'Korelasi Pearson: {corr_value:.2f}',
         fontsize=12, bbox=dict(facecolor='white', alpha=0.5))

plt.title('Korelasi Suhu (Normalized) terhadap Jumlah Penyewaan', fontsize=15, loc='left', pad=20)
plt.xlabel('Suhu Udara (Normalized)', fontsize=12)
plt.ylabel('Total Penyewaan Harian', fontsize=12)

sns.despine()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

"""**Insight:** (Opsional)
- Terdapat hubungan linear positif yang kuat dengan korelasi pearson sebesar 0.63 anata suhu dan jumlah sewa sepeda.
- Semakin hangat suhu udara (hingga titik tertentu), semakin tinggi minat masyarakat untuk bersepeda.
- Sebaran data menunjukkan kepadatan yang tinggi pada suhu menengah ke atas, yang berarti cuaca hangat adalah pemicu utama pendapatan bisnis ini.

## Analisis Lanjutan (Opsional)

Pada bagian ini, saya menerapkan dua teknik analisis tambahan untuk mendapatkan insight yang lebih komprehensif:
1. RFM Analysis: Untuk melihat kapan transaksi terakhir terjadi (Recency), seberapa sering volume tinggi tercapai (Frequency), dan total volume penyewaan (Monetary) berdasarkan bulan.
2. Manual Grouping (Clustering): Mengategorikan hari-hari ke dalam tingkat performa penyewaan (Low, Mediun, High) untuk melihat distribusi produktivitas harian tanpa menggunakan algoritma Machine Learning.

### Analisis Lanjutan 1 (RFM)
"""

# Menentukan tanggal referensi (satu hari setelah data terakhir)
recent_date = day_df['dteday'].max() + pd.Timedelta(days=1)

# Recency: Selisih hari sejak transaksi terakhir di bulan tersebut
# Frequency: Jumlah hari transaksi dalam sebulan
# Monetary: Total volume penyewaan dalam sebulan
rfm_df = day_df.groupby(by="mnth", observed=False).agg({
    "dteday": lambda x: (recent_date - x.max()).days,
    "cnt": ["count", "sum"]
})

rfm_df.columns = ["recency", "frequency", "monetary"]

print("RFM Analysis Berdasarkan Bulan:")
display(rfm_df)

"""**Insight:**
- Nilai Recency menurun drastis hingga 1 hari pada bulan Desember. Menunjukkan bahwa data up-to-date hingga akhir tahun 2012, memberikan validitas tinggi untuk perencanaan strategi di awal tahun berikutnya.
- Jumlah hari transaksi (frequency) stabil di angka 60-62 hari (total dari 2011 & 2012). Mengindikasikan layanan beroperasi penuh tanpa gangguan teknis atau penutupan operasional yang signifikan di setiap bulannya.
- Terjadi tren kenaikan monetary yang konsisten mulai dari Maret dan mencapai puncaknya pada Agustus (351.194 penyewaan). Menariknya, performa mulai menurun saat memasuki November-Desember.
- Periode Mei hingga Oktober adalah "Golden Months" di mana volume penyewaan selalu di atas 300.000. Perusahaan harus memastikan armada sepeda dalam kondisi prima di bulan-bulan ini.

### Analisis Lanjutan 2 (Manual Grouping)
"""

# Menentukan kriteria binning (Low, Medium, High)
bins = [0, 3100, 6000, day_df['cnt'].max()]
labels = ['Low Performance', 'Medium Performance', 'High Performance']
day_df['rental_category'] = pd.cut(day_df['cnt'], bins=bins, labels=labels)

# Persiapan canvas
plt.figure(figsize=(10, 6))

# Menggunakan palet warna yang konsisten dan kontras
ax = sns.countplot(
    x='rental_category',
    data=day_df,
    palette='viridis',
    order=labels
)

# Menambahkan Anotasi Angka
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())} hari',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 10),
                textcoords='offset points',
                fontsize=11,
                fontweight='bold')

# Membersihkan Elemen Visual
plt.title('Distribusi Performa Penyewaan Harian (2011-2012)', fontsize=14, pad=20, loc='left')
plt.xlabel(None)
plt.ylabel('Jumlah Hari')
plt.ylim(0, day_df['rental_category'].value_counts().max() + 50) # Memberi ruang untuk anotasi

sns.despine() # Mengurangi Chartjunk (Prinsip Tufte)
plt.tight_layout()
plt.show()

# Menampilkan proporsi untuk mendukung Integritas Data
print("Proporsi Kategori Performa (Persentase):")
print(day_df['rental_category'].value_counts(normalize=True) * 100)

"""**Insight:**
- Lebih dari separuh total hari operasional (51% atau 373 hari) berada pada kategori Medium Performance (3.100 - 6.000 sewa). Ini menunjukkan bahwa bisnis memiliki basis permintaan harian yang stabil dan sehat.
- Terdapat proporsi yang hampir seimbang antara Low Performance (24,3%) dan High Performance (24,6%).
- Low Performance (178 hari): Kemungkinan besar terjadi pada hari-hari di musim dingin atau saat kondisi cuaca ekstrim (seperti yang terlihat pada analisis cuaca sebelumnya).
- High Performance (180 hari): Menunjukkan bahwa dalam 2 tahun, ada sekitar 6 bulan total di mana bisnis mencapai kapasitas maksimal (di atas 6.000 sewa).
- Grafik ini mengonfirmasi bahwa pertumbuhan yang ditemukan di analisis tahunan (64,8%) didorong oleh banyaknya hari yang berhasil masuk ke kategori Medium dan High, bukan sekadar lonjakan di hari-hari tertentu saja.

## Conclusion & Recommendation

- **Conclusion pertanyaan 1:** Kondisi cuaca merupakan faktor penentu paling krusial terhadap jumlah penyewaan sepeda. Di tahun 2012, cuaca cerah (Clear/Partly Cloudy) menghasilkan rata-rata penyewaan tertinggi (6.004 unit), sedangkan kondisi cuaca buruk (Light Snow/Rain) menurunkan minat sewa hingga 64% menjadi hanya 2.126 unit. Ini membuktikan bahwa kenyamanan visual dan keamanan berkendara sangat memengaruhi keputusan pengguna.
- **Conclusion pertanyaan 2:** SPola penyewaan di musim gugur bersifat dinamis dan fluktuatif. Aktivitas rekreasi mendominasi di awal musim (Juni) dengan angka tertinggi pada hari libur (6.108 unit). Sebaliknya, pada tengah musim (Agustus), fungsi sepeda bergeser menjadi transportasi utama untuk bekerja/rutinitas harian dengan keunggulan pada hari kerja (5.908 unit). Secara umum, musim gugur adalah periode "panen" bagi bisnis karena jumlah sewa tetap stabil di angka yang tinggi (5.000+) baik pada hari kerja maupun libur.
- **Conclusion Pertanyaan 3:** Bisnis bike sharing ini menunjukkan performa yang luar biasa dengan pertumbuhan tahunan (Year-over-Year) sebesar 64,8%. Lonjakan total penyewaan dari 1,24 juta di tahun 2011 menjadi 2,05 juta di tahun 2012 mengindikasikan bahwa model bisnis ini sangat berkelanjutan (sustainable) dan memiliki basis pelanggan yang terus berekspansi secara masif.
- **Conclusion Pertanyaan 4:** Terdapat hubungan linear positif yang kuat (0,63) antara suhu udara dengan jumlah penyewaan. Semakin hangat suhu udara (dalam rentang normal), semakin tinggi kecenderungan masyarakat untuk menyewa sepeda. Analisis ini mempertegas bahwa pengguna sangat mempertimbangkan "kenyamanan termal" sebelum memutuskan untuk berkendara.
- **Conclusion Analisis Lanjutan:** Bisnis mengalami pertumbuhan yang sangat positif dengan lonjakan total penyewaan hampir dua kali lipat dari tahun 2011 ke 2012 (melampaui 2 juta unit). Analisis korelasi Pearson sebesar 0.63 mengonfirmasi bahwa suhu udara adalah prediktor kuat, semakin hangat suhu, semakin tinggi minat masyarakat untuk menyewa sepeda. Selain itu, basis pengguna *registered* merupakan mayoritas stabilitas pendapatan perusahaan di segala musim.

**Rekomendasi Action Item:**
- Integrasikan sistem operasional dengan API prakiraan cuaca harian. Pada hari-hari yang diprediksi akan turun hujan atau salju, perusahaan dapat menjadwalkan pemeliharaan unit besar-besaran karena permintaan sedang rendah, guna memastikan ketersediaan unit 100% saat cuaca kembali cerah.
- Mengingat pengguna registered jauh lebih stabil terhadap perubahan musim, perusahaan perlu meluncurkan kampanye pemasaran untuk mengonversi pengguna casual. Implementasikan promo langganan musiman "Golden Months" (Mei-Oktober) untuk mengunci loyalitas pengguna selama periode puncak Monetary di hasil analisis RFM.
- Berdasarkan temuan di bulan Juni dan September, tim operasional harus meningkatkan distribusi sepeda di titik-titik rekreasi dan taman kota pada akhir pekan. Strategi "Weekend Bundling" atau paket keluarga pada hari libur di bulan-bulan ini dapat memaksimalkan potensi pendapatan dari sektor rekreasi yang terbukti mencapai angka 6.108 sewa.
- Melihat tren pertumbuhan tahunan yang masif (64,8%), perusahaan memiliki peluang besar untuk melakukan ekspansi stasiun sepeda baru di wilayah perkantoran dan jalur komuter. Fokus pada kategori "Medium Performance" yang mendominasi 51% hari operasional menunjukkan adanya permintaan harian yang stabil yang perlu difasilitasi dengan kemudahan akses.
- Untuk 178 hari yang masuk dalam kategori *Low Performance* (24,3% dari total hari), perusahaan disarankan membuat aktivasi event atau promo "Anti-Mager" di aplikasi saat suhu udara menurun, guna menstimulasi ketersinggungan korelasi positif antara suhu dan jumlah sewa.

## Exporting Cleaned Data for Dashboard
"""

day_df.to_csv("main_data.csv", index=False)